name: Duplicate Issue to Other Repositories

on:
  issues:
    types: [opened]

jobs:
  duplicate_issue:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'duplicate-to-other-repos')
    env:
      REPOS: |
        Itsuki54/kizino_niwa 
        Itsuki54/portfolio
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Remove label
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.payload.issue.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const label = 'duplicate-to-other-repos';

            await github.issues.removeLabel({
              owner,
              repo,
              issue_number,
              name: label
            });

      - name: Duplicate issue
        uses: actions/github-script@v7
        with:
          script: |
            const repos = process.env.REPOS.split('\n').filter(repo => repo);
            const issue_title = context.payload.issue.title;
            const issue_body = context.payload.issue.body;

            const labels = context.payload.issue.labels
              .map(label => label.name)
              .filter(name => name !== 'duplicate-to-other-repos');

            for (const repo of repos) {
              const [owner, repoName] = repo.split('/');
              await github.issues.create({
                owner,
                repo: repoName,
                title: issue_title,
                body: issue_body,
                labels
              });
            }
