name: Duplicate Issue to Other Repositories

on:
  issues:
    types: [opened]

jobs:
  duplicate_issue:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'duplicate-to-other-repos')
    env:
      REPOS: |
        Itsuki54/kizino_niwa 
        Itsuki54/portfolio
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Remove label
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.payload.issue.number;
            const repo = context.repo;
            const label = "duplicate-to-other-repos";

            await github.issues.removeLabel({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: issueNumber,
              name: [label],
            });

      - name: Duplicate issue
        uses: actions/github-script@v6
        with:
          script: |
            const repos = process.env.REPOS.split("\n").filter(Boolean);
            const issue = context.payload.issue;

            // Exclude the 'duplicate-to-other-repos' label
            const labels = issue.labels
              .map(label => label.name)
              .filter(name => name !== "duplicate-to-other-repos");

            for (const repo of repos) {
              const [owner, repoName] = repo.split("/");
              await github.issues.create({
                owner,
                repo: repoName,
                title: issue.title,
                body: issue.body,
                labels,
              });
            };
