name: Duplicate Issue to Other Repositories

on:
  issues:
    types: [opened, labeled]

jobs:
  duplicate_issue:
    runs-on: ubuntu-latest
    if: contains(join(github.event.issue.labels.*.name), 'duplicate-to-other-repos')
    env:
      REPOS: |
        Itsuki54/portfolio
        Itsuki54/kizino_niwa
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: algo-method/algo-method-4c-web
          token: ${{ secrets.TOKEN }}

      - name: Remove label
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.payload.issue.number;
            const repo = context.repo;
            const label = "duplicate-to-other-repos";

            await github.rest.issues.removeLabel({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: issueNumber,
              name: label,
            });

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Duplicate issue
        run: |
          repos=(Itsuki54/portfolio Itsuki54/kizino_niwa)

          issue_title="${{ github.event.issue.title }}"
          issue_body="${{ github.event.issue.body }}"

          labels=$(echo '${{ toJson(github.event.issue.labels.*.name) }}' | jq 'map(select(. != "duplicate-to-other-repos")) | @json')

          for repo in "${repos[@]}"; do
            curl -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/$repo/issues \
              -d "$(jq -n --arg title "$issue_title" \
                            --arg body "$issue_body" \
                            --argjson labels "$labels" \
                            '{title: $title, body: $body, labels: $labels}')"
          done

permissions:
  issues: write
